### ISSUE TITLE
Map single gene-expression profile to lmQCM output

### ISSUE THREAD

**Issue by ManuTel** [huangzhii/lmQCM#3]
Is there any way we can map a new vector of gene-expression profile to already calculated gene co-expression network using lmQCM? For example, we can project a new data point to already calculated PCA components explained here: https://stats.stackexchange.com/questions/2592/how-to-project-a-new-vector-onto-pca-space

**Comment by huangzhii** [comment]
Thank you for your comment. I am afraid not. If there's a new vector of the gene-expression profile, the practical way is to re-run the program instead of mapping on-the-fly. Because lmQCM needs to find the maximum values row-wise/column-wise, any new vector coming in will require an entirely new running.
